### PR TITLE
Crystal/v0.25.0

### PR DESCRIPTION
**Pull request by bcardiff**
This PR updates to future breaking changes in crystal 0.25
This includes the https://github.com/mosop/teeplate/pull/9 which are not merged.

cc: @paulcsmith , @faustinoaq both amber and lucky use teeplate. Lucky uses currently my branch fork and amber has forked the repo inside the organization. I am not sure if @mosop is still interested in maintaining this repo, but seems there is interest in it from both framworks. Maybe it can be moved/forked in a common place like crystal-community org.

### CODE REVIEW

**Comment by paulcsmith** [comment]
Thanks for the ping! Teeplate is a wonderful package and I'd love to see it continue to be maintained somewhere. I have too many shards already to help out, but maybe Amber team or someone else in the Crystal community would like to maintain it?

**Comment by robacarp** [comment]
My preference would be for it to live under crystal-community

**Comment by drujensen** [comment]
I vote for crystal-community as well

**Comment by veelenga** [comment]
Let me know and I will grant @mosop rights to move the repo.

Just for the notice: crystal-community usually doesn't evolve the project very much. I've seen people review/merge PRs, prepare releases but don't create new features or work on the issues. If you want the project to grow, you still need to find a maintainer.

**Comment by elorest** [comment]
Amber is currently using it. I doubt that we'll change much but we at least
have an incentive to keep it working.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by elorest** [comment]
Amber is currently using it. I doubt that we'll change much but we at least
have an incentive to keep it working.

**Comment by mosop** [comment]
Hi. Crystal can't run on my macOS now! Why is travis failed?

By the way, how about to create a dedicated organization for this library? And I can easily give rights to you contributors.

**Comment by mosop** [comment]
Finally fixed! Use v0.6.1 for the new Crystal 0.25, and v0.5.0 for 0.24.2. Thank you all!

**Comment by paulcsmith** [comment]
Thanks @mosop! This library has been incredibly helpful on Lucky. I really appreciate all the work you've done :)

**Comment by drujensen** [comment]
@mosop This library has been incredibly helpful to Amber as well.  We all really appreciate the work you have done!  :-D

**Pull request merged**
